services:
  discordreactbot:
    image: ${DOCKER_REGISTRY-}discordreactbot
    build:
      context: .
      dockerfile: DiscordReactBot/Dockerfile
    volumes:
      - ./config/config.json:/app/config.json
